server:
  port: 8080

## MySQL

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:booking-dev}?sessionVariables=sql_mode=''&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: ${DB_USER_NAME:root}
    password: ${DB_PASSWORD:root}
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: create
    show-sql: true
    generate-ddl: true
    database: MYSQL
    open-in-view: false

logging:
  level:
    com.transperfect: info
    root: info
    org.hibernate: info
    org.springframework.web: info
  file:
    name: ${java.io.tmpdir}/service.log