server:
  port: 8080

## MySQL

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sessionVariables=sql_mode=''&createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        dialect: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      # Hibernate ddl auto (create, create-drop, update)
      ddl-auto: validate
    show-sql: false
    generate-ddl: true
    database: MYSQL
    open-in-view: false

logging:
  level:
    com.transperfect: debug
    root: debug
    org.hibernate: debug
    org.springframework.web: debug
  file:
    name: ${java.io.tmpdir}/service.log