spring:
  profiles:
    active: @spring.profiles.active@
  main:
    allow-circular-references: true
  jpa:
    defer-datasource-initialization: true
    properties:
      hibernate:
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 10
  servlet:
    multipart:
      max-file-size: 3MB
  liquibase:
    drop-first: false
    enabled: false
    change-log: classpath*:db/changelog/db.changelog-master.xml

springdoc:
  swagger-ui:
    path: /booking-documentation.html
    operationsSorter: method
    server:
      url: ${SERVER_URL:http://localhost:8080}

booking:
  time:
    initialAvailableBookingWeekDayNumber: 1
    finalAvailableBookingWeekDayNumber: 5
    initialAvailableBookingHours: 9
    finalAvailableBookingHour: 17
